### PR TITLE
fix: remove gameInit throw #125

### LINKED ISSUE #125: Graceful gameInit failure
I accidentally created a stage with a null duration today, and (quite reasonably) it threw an error.

```console
2020-05-04 12:38:48-04:00"round.addStage()" requires an argument object with 3 properties:
2020-05-04 12:38:48-04:00- name: internal name you'll use to write conditional logic in your experiment.
2020-05-04 12:38:48-04:00- displayName: the name of the Stage the player will see in the UI.
2020-05-04 12:38:48-04:00- durationInSeconds: the duration in seconds of the stage
...
2020-05-04 12:38:48-04:00Got: {
2020-05-04 12:38:48-04:00 "name": "message",
2020-05-04 12:38:48-04:00 "displayName": "Message",
2020-05-04 12:38:48-04:00 "durationInSeconds": null
2020-05-04 12:38:48-04:00}
...
2020-05-04 12:38:48-04:00fatal error encounter calling Empirica.gameInit:
2020-05-04 12:38:48-04:00gameInit error
2020-05-04 12:38:50-04:00Players.methods.ready at least one stage must be added per round
```

 However, it also canceled all other simultaneously running games within the batch.

## Expected Behavior
I would expect that a fault in on one game in the batch would not preclude other games from finishing - or if the experimenter wants to immediately discard batches with errors, this behavior would be a setting.

## Possible Solution
Add game-level error handling to protect remaining games

## version:
empirica @ https://github.com/empiricaly/meteor-empirica-core/commit/92903252bdda34ddd62aade459a580517dc87565

### PR DESCRIPTION
**Pull request by hubertusputu1**
## Description

will not throw error when there is one of stage is invalid, instead we will end game and move players into exit with status failed. 

## Motivation and Context

https://github.com/empiricaly/meteor-empirica-core/issues/125

## How Has This Been Tested?

tested with first stage with invalid duration (null), game didn't throw. status on each player and game was failed. 

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by npaton — CHANGES_REQUESTED** [review]
I don't know if we continue with game creation. I feel like we should cancel the game. If say there's only one round, and the init failed, then there's no game to play. Maybe we mark the game as failed (ended reason: initError) and send players to exit (player exit with reason failedGame) with failed game state?

**Comment by hubertusputu1** [comment]
@npaton I agree on that one. I have added a new `failed` state for game and playersj, also end game and players if `gameInit` is failed.

**Comment by JamesPHoughton** [comment]
Agree that if the game has an error it should spit players out to the exit. 

The problem I had encountered in https://github.com/empiricaly/meteor-empirica-core/issues/125 could be broader than just a bad stage. If other errors happen in a particular game (maybe a resource is missing, a bot throws an error, or any number of things) we would want some sort of game-level try...catch that would prevent a generic error in one game from spilling over to affect other games.

**Review by npaton — APPROVED** [review]
LGTM!

@JamesPHoughton So catching on any callback errors cleanly and ending the game? That should definitely be the case. I believe the app does not explode anymore, so there it shouldn't affect other games, but I don't think we cancel the game at the moment. I will close this PR and create a new ticket to track that.

**Comment by npaton** [comment]
Created issue to track the catching of any callback error: #133

**Pull request merged**
