### PR TITLE
Add a timestamp to Stage key/value data

### PR DESCRIPTION
**Pull request by shawnzam**
## Description

Added a timestamp field as a default value in the stage data object.

## Motivation and Context

This will be helpful when using the https://github.com/empiricaly/chat plugin.

## How Has This Been Tested?

This has been testing using the Chat plugin.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ x] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by JamesPHoughton** [comment]
Hi @shawnzam!

I've been working on timestamps for chat too, sorry if we're duplicating work. I just created https://github.com/empiricaly/chat/pull/4 in the chat plugin that should handle timestamping with server-side timestamps (assuming @npaton agrees!). I've had trouble with client-side timestamps not lining up in some experiments, which can invalidate the data. 

Putting the timestamp in the chat component may help if we're passing the chat component a different scope (game, round, etc)?

It's worth asking, though, whether the .set, .append methods want timestamps. `player.log()` keeps a timestamp, but I think the timestamp is created server-side based on when the value enters the database? @amaatouq, is this how things work?

James

**Comment by shawnzam** [comment]
@JamesPHoughton 

Thanks for the note. From what I can see, setting the timestamp server side is the way to go, but I am not sure if setting it in the `.append` and `.set` fns is the cleanest. I am certainly open to @amaatouq's input.

On a similar note, how are you doing dev on the chat module? Currently I have my directories organized like:

```
.
├── chat
├── meteor-empirica-core
└── my-experiment
```
and when I launch meteor I can specify my dev version of meteor-empirica-core like 

```
$ cd my-experiment/
$ METEOR_PACKAGE_DIRS=".." meteor
```

But how can I use a local dev copy of the chat repository?

**Comment by JamesPHoughton** [comment]
This is *not* the correct way to do it, but I have the chat code within my experiment/client folder, next to `game`, `exit`, and `intro`, and then just use relative imports. 🧐

**Comment by shawnzam** [comment]
@JamesPHoughton Using the method you describe I am seeing the following error 

```
modules.js?hash=5190bef78979b15d95ade849c2544a67629e0829:21554 Warning: Failed prop type: The prop `scope` is marked as required in `Messages`, but its value is `undefined`.
    in Messages (created by PureComponent)
    in PureComponent (created by Chat)
    in div (created by Chat)
    in div (created by Chat)
    in div (created by Chat)
    in Chat (created by Round)
    in div (created by Round)
    in div (created by Round)
    in Round
    in div
    in Game (created by ReactMeteorDataComponent)
    in ReactMeteorDataComponent (created by ReactMeteorDataComponent)
    in ReactMeteorDataComponent (created by ReactMeteorDataComponent)
    in ReactMeteorDataComponent
    in main
    in div
    in Public (created by ReactMeteorDataComponent)
    in ReactMeteorDataComponent (created by ReactMeteorDataComponent)
    in ReactMeteorDataComponent (created by ReactMeteorDataComponent)
    in ReactMeteorDataComponent
    in IdentifiedContainerInner (created by ReactMeteorDataComponent)
    in ReactMeteorDataComponent
    in Route
    in Switch
    in div
    in Router
    in BrowserRouter
```

with `my-experiment/client`:

```.
├── exit
│   ├── ExitSurvey.jsx
│   └── Thanks.jsx
├── game
│   ├── About.jsx
│   ├── Chat.js
│   ├── Footer.js
│   ├── GameLobby.js
│   ├── Header.js
│   ├── LobbyChat.js
│   ├── Message.js
│   ├── Messages.js
│   ├── PlayerProfile.jsx
│   ├── Round.jsx
│   ├── SocialExposure.jsx
│   ├── Task.jsx
│   ├── TaskResponse.jsx
│   ├── TaskStimulus.jsx
│   ├── Timer.jsx
│   ├── index.js
│   └── style.less
├── intro
│   ├── Consent.jsx
│   ├── InstructionStepOne.jsx
│   ├── InstructionStepTwo.jsx
│   └── Quiz.jsx
├── main.html
├── main.js
└── main.less
```

I am calling the component like 

```          
<Chat player={player} scope={round} customKey={'chat'} />;
```

I am sure that the `this.props.scope` is correctly making it to the `Chat` component. Any ideas?

edit: I have never worked with Higher-Order Components before in React.

**Comment by npaton** [comment]
Hey Shawn. If you are embedding the code, it might be easier to seperate the chat folder and use a relative import.

```js
import { Chat } from "../chat"
```

```
├── exit
│   ├── ExitSurvey.jsx
│   └── Thanks.jsx
├── chat
│   ├── Chat.js
│   ├── Footer.js
│   ├── GameLobby.js
│   ├── Header.js
│   ├── LobbyChat.js
│   ├── Message.js
│   ├── Messages.js
│   ├── index.js
│   └── style.less
├── game
│   ├── About.jsx
│   ├── PlayerProfile.jsx
│   ├── Round.jsx
│   ├── SocialExposure.jsx
│   ├── Task.jsx
│   ├── TaskResponse.jsx
│   ├── TaskStimulus.jsx
│   └── Timer.jsx
├── intro
│   ├── Consent.jsx
│   ├── InstructionStepOne.jsx
│   ├── InstructionStepTwo.jsx
│   └── Quiz.jsx
├── main.html
├── main.js
└── main.less
```

For the scope, it's hard to tell without seeing the full contact of the <Chat> usage. If you want to/can share code with me, I can take a closer look.

As for the timestamp, it is not safe to assume the value of append will be an object. There is no requirement for set/append values to be objects, so we cannot just insert a timestamp like that.

@JamesPHoughton change in the Chat should do the job. And the timestamp used is synchronized from the server, so it's relatively reliable in that regard. It is not completely tamper proof, but unlikely to be tampered with.

I am going to close this PR, feel free to reopen an issue with your import/scope problem, maybe in the chat repo. And we'll try to release a new version of the Chat soon to add the timestamp.

**Comment by hubertusputu1** [comment]
Chat v1.1 released with timestamps added to messages

**Comment by JamesPHoughton** [comment]
Hey @shawnzam, 
I'm doing what npaton suggests - his directory structure is the same as mine. 
James

**Pull request closed without merging**
